---
role:
  pkg: # virtualenv, pyenv, pipenv...
    - name: python
      action: install
    - name: python2
      action: install
      os: ["android"]
    - name: python3
      action: install
      os: ["!android", "!centos"]
    # Fix termux npm install neovim
    - name: libcrypt-dev
      #   - python2-dev
      #   - python-dev
      os: ["android"]
    - name:
        - build-base
        - python2-dev
        - python3-dev
        # - py{2,3}-udev
        # - py-setuptools
        # - py3-setuptools
      os: ["alpine"]
    - name:
        # - python-dev
        # - python3-dev
        - python-setuptools
        - python3-setuptools
      os: ["debian"] # cygwin
    - name: py-pip # py2-pip
      os: ["alpine"]
    - name: python2-pip
      os: ["archlinux"]
    - name: python-pip # centos: epel-release
      os: ["archlinux", "centos", "debian"]
    - name: python3-pip
      os: ["debian"]
  post_install:
    - python --version
    - command: |
        sudo yum install --quiet -y python36-setuptools;
        sudo easy_install-3.6 pip
      # if: '[ "$DOT_PKG" -eq 1 ]'
      os: ["centos"]
    # TODO symlink python3 to python36 (centos)
    - python3 --version || python36 --version
    # - command: pip install --upgrade --user pip
    - command: ln -s $(which pip) $(which pip)3
      if: "[ -f $(which pip) ] && ! hash pip3"
      os: ["android"]
    - command: |
        sudo pip2 install --upgrade pip
        sudo pip3 install --upgrade pip
      os: ["alpine"]
    # - command: |
    #     pip2 install --quiet --user setuptools wheel
    #     pip3 install --quiet --user setuptools wheel
    #   os: ["alpine"]
    - pip --version
    - pip2 --version
    - pip3 --version
    # - command: pip install{{if .OS "darwin"}} --user python{{end}} pip
    #   os: ["!arch"]
    # pip3: --no-cache-dir
