---
role:
  pkg:
    - python
    - python3
    - name: python-pip
      os: ["arch", "centos"]
    # - name: python-dev python3-dev
    #   os: ["debian"]
    # - name: python-setuptools
    #   os: ["cygwin"]
  post_install:
    - python --version
    - python3 --version
    - pip --version
    - pip3 --version
    # - command: pip install{{if .OS "darwin"}} --user python{{end}} pip
    #   os: ["!arch"]
    # pip3: --no-cache-dir
