---
role:
  pkg:
    - name: python
      action: install
    - name: python3
      action: install
      os: ["!centos"]

    - name: py-pip
      os: ["alpine"]
    - name: python-pip # centos: epel-release
      os: ["arch", "centos", "debian"]
    # - name: python2-pip
    #   os: ["arch"]
    - name: python3-pip
      os: ["debian"]
    # - name: python-dev python3-dev
    #   os: ["debian"]

    - name:
        - py-setuptools
        - py3-setuptools
      os: ["alpine"]
    - name:
        - python-setuptools
        - python3-setuptools
      os: ["debian"] # cygwin

    # TODO: virtualenv
  post_install:
    - python --version
    - command: |
        sudo yum install --quiet -y python36-setuptools;
        sudo easy_install-3.6 pip
      os: ["centos"]
    - python3 --version || python36 --version
    - pip --version
    - command: pip2 --version
      os: ["!archlinux"]
    - pip3 --version
    # - command: pip install{{if .OS "darwin"}} --user python{{end}} pip
    #   os: ["!arch"]
    # pip3: --no-cache-dir
