---
role:
  pkg:
    - name: python
      action: install
    - name: python3
      action: install
      os: ["!centos"]

    - name: py-pip # py2-pip
      os: ["alpine"]
    - name: python2-pip
      os: ["archlinux"]
    - name: python-pip # centos: epel-release
      os: ["archlinux", "centos", "debian"]
    - name: python3-pip
      os: ["debian"]
    # - name: python-dev python3-dev
    #   os: ["debian"]

    # - name:
    #     # - python2-dev
    #     # - python3-dev
    #     # - py{2,3}-udev
    #     - py-setuptools
    #     - py3-setuptools
    #   os: ["alpine"]
    - name:
        - python-setuptools
        - python3-setuptools
      os: ["debian"] # cygwin

    # TODO: virtualenv
  post_install:
    - python --version
    - command: |
        sudo yum install --quiet -y python36-setuptools;
        sudo easy_install-3.6 pip
      os: ["centos"]
    # - command: pip install --upgrade --user pip
    - command: sudo pip install --upgrade pip
      os: ["alpine"]
    - python3 --version || python36 --version
    - pip --version
    - pip2 --version
    - pip3 --version
    # - command: pip install{{if .OS "darwin"}} --user python{{end}} pip
    #   os: ["!arch"]
    # pip3: --no-cache-dir
